/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ResponsableDAO;
import Entities.Categorie;
import Entities.Domaine;
import Entities.Responsable;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author A500
 */
public class modifierCompteResp extends javax.swing.JFrame {
       ResponsableDAO respDAO=new ResponsableDAO();
       Responsable resp;
    /**
     * Creates new form modifierCompteResp
     */
    public modifierCompteResp() {
        initComponents();
        jPanel5.setVisible(false);
        jButtonValider.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAncienMail = new javax.swing.JTextField();
        jTextFieldCIN = new javax.swing.JTextField();
        jPasswordFieldAncienPwd = new javax.swing.JPasswordField();
        jButtonVerifiier = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxCategorie = new javax.swing.JComboBox();
        jComboBoxDomaine = new javax.swing.JComboBox();
        jTextFieldNouvMail = new javax.swing.JTextField();
        jTextFieldGrade = new javax.swing.JTextField();
        jTextFieldTelephone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPwdNouv2 = new javax.swing.JPasswordField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNouvAdresse = new javax.swing.JTextField();
        jTextFieldpwd = new javax.swing.JTextField();
        jButtonValider = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonQuitter = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();
        jButtonAccueil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel22.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 0, 0));
        jLabel22.setText("Tunisian Watch");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(195, 195, 195)
                .add(jLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 407, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel22, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(21, 21, 21))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations de connexion"));

        jLabel1.setText("E-Mail");

        jLabel3.setText("CIN");

        jLabel4.setText("Ancien mot de passe");

        jTextFieldAncienMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAncienMailActionPerformed(evt);
            }
        });

        jTextFieldCIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCINActionPerformed(evt);
            }
        });

        jButtonVerifiier.setText("Verifier >>");
        jButtonVerifiier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerifiierActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jButtonVerifiier)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3)
                                    .add(jLabel1))
                                .add(81, 81, 81))
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)))
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextFieldAncienMail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFieldCIN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPasswordFieldAncienPwd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jTextFieldAncienMail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(32, 32, 32))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(18, 18, 18)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextFieldCIN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 13, Short.MAX_VALUE)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jPasswordFieldAncienPwd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .add(18, 18, 18)
                .add(jButtonVerifiier)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Actualiser mes infos"));

        jLabel5.setText("Adresse E-Mail");

        jLabel6.setText("Mot de passe");

        jLabel7.setText("Grade");

        jLabel8.setText("Date de naissance");

        jLabel9.setText("Numero de telephone ");

        jLabel10.setText("Categorie");

        jLabel11.setText("Domaine ");

        jComboBoxCategorie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Etatique", "Semi Etatique", "Prive" }));

        jComboBoxDomaine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sante", "Education", "Logement", "Transport", "Commerce", "Indestrie", "Agriculture", "Autre" }));

        jLabel12.setText("Re - Mot de passe");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        jTextFieldPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomActionPerformed(evt);
            }
        });

        jLabel13.setText("Nom");

        jLabel14.setText("Prénom");

        jLabel15.setText("Adresse ");

        jTextFieldNouvAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNouvAdresseActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(jLabel6)
                            .add(jLabel12)
                            .add(jLabel13)
                            .add(jLabel14))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jTextFieldNom)
                            .add(jTextFieldPrenom)
                            .add(jTextFieldNouvMail, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .add(jPwdNouv2)
                            .add(jTextFieldpwd)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel7)
                            .add(jLabel9)
                            .add(jLabel10))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 117, Short.MAX_VALUE)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jComboBoxCategorie, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jTextFieldTelephone)
                            .add(jTextFieldGrade, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel8)
                            .add(jLabel11)
                            .add(jLabel15))
                        .add(99, 99, 99)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jComboBoxDomaine, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jDateChooser1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .add(jTextFieldNouvAdresse))))
                .add(79, 79, 79))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldNom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldPrenom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel14))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jTextFieldNouvMail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(9, 9, 9)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(jTextFieldpwd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(jPwdNouv2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldGrade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldTelephone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9))
                .add(8, 8, 8)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxCategorie, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10))
                .add(11, 11, 11)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(jComboBoxDomaine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel8)
                    .add(jDateChooser1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(11, 11, 11)
                        .add(jLabel15))
                    .add(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextFieldNouvAdresse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButtonValider.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonValider.setText("Enregistrer");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Modifer compte");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Inscription.jpg"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 278, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(46, 46, 46))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                                .add(jLabel16)
                                .add(77, 77, 77))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))))
                .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(14, 14, 14))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jButtonValider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(102, 102, 102))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel16))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE)))
                .add(18, 18, 18)
                .add(jButtonValider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonQuitter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonQuitter.setText("Quitter");
        jButtonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitterActionPerformed(evt);
            }
        });

        jButtonRetour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        jButtonAccueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo-accueil.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButtonQuitter, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButtonRetour, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .add(32, 32, 32)
                .add(jButtonAccueil, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(119, 119, 119)
                .add(jButtonAccueil, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonRetour, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonQuitter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(90, 90, 90))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAncienMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAncienMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAncienMailActionPerformed

    private void jTextFieldCINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCINActionPerformed

    private void jButtonVerifiierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerifiierActionPerformed
           int c=Integer.parseInt(jTextFieldCIN.getText()); 
           ResponsableDAO rd= new ResponsableDAO();
           resp=rd.findResponsableById(c);
           Component frame = null;

       //------------------------test---------------    
           if (jTextFieldAncienMail.getText().equals(resp.getEmail()) && (jPasswordFieldAncienPwd.getText().equals(resp.getPwd()))   && (c==resp.getCin())   ){
           jPanel5.setVisible(true); 
           jButtonValider.setVisible(true);
           }
           else { 
           JOptionPane.showMessageDialog(frame,"verifier vos donnees");
           }
       //-------------------------recuperer les donnees a partir de la base dans les champs
           resp=rd.displayResponsableById(c);
           jTextFieldNom.setText(resp.getNom());
           jTextFieldPrenom.setText(resp.getPrenom());
           jTextFieldNouvAdresse.setText(resp.getEmail());
           jTextFieldpwd.setText(resp.getPwd());
           jTextFieldGrade.setText(resp.getGrade());
           jTextFieldTelephone.setText(""+resp.getTelephone());
           jDateChooser1.setDate(resp.getDateNaissance());
           jTextFieldNouvMail.setText(resp.getEmail());
           jDateChooser1.setDate(resp.getDateNaissance());
          
          
           
           if(resp.getCategorie().equals(Categorie.prive)){
            jComboBoxCategorie.removeAllItems();
            jComboBoxCategorie.addItem("prive");
            jComboBoxCategorie.addItem("etatique");
            jComboBoxCategorie.addItem("semiEtatique");
           }
           else if(resp.getCategorie().equals(Categorie.semiEtatique)){
            jComboBoxCategorie.removeAllItems();
            jComboBoxCategorie.addItem("semiEtatique");
            jComboBoxCategorie.addItem("etatique");
            jComboBoxCategorie.addItem("prive");   
           }else if(resp.getCategorie().equals(Categorie.etatique)) {
            jComboBoxCategorie.removeAllItems();
             jComboBoxCategorie.addItem("etatique");
            jComboBoxCategorie.addItem("semiEtatique");
            jComboBoxCategorie.addItem("prive");
           }
           
           if(resp.getDomaineTravail().equals(Domaine.santé)){
               jComboBoxDomaine.removeAllItems();
               jComboBoxDomaine.addItem("santé");
               jComboBoxDomaine.addItem("agriculture");
               jComboBoxDomaine.addItem("commerce");
               jComboBoxDomaine.addItem("education");
               jComboBoxDomaine.addItem("industrie");
               jComboBoxDomaine.addItem("logement");  
               jComboBoxDomaine.addItem("transport");
               jComboBoxDomaine.addItem("autre");  
           } 
            
    
           else if((resp.getDomaineTravail().equals(Domaine.transport))){
                jComboBoxDomaine.removeAllItems();
                jComboBoxDomaine.addItem("transport");
                jComboBoxDomaine.addItem("agriculture");
                jComboBoxDomaine.addItem("commerce");
               jComboBoxDomaine.addItem("education");
               jComboBoxDomaine.addItem("indestrie");
               jComboBoxDomaine.addItem("logement"); 
               jComboBoxDomaine.addItem("santé");
               jComboBoxDomaine.addItem("autre");  
            }

            else if((resp.getDomaineTravail().equals(Domaine.logement))){
                jComboBoxDomaine.removeAllItems();
                jComboBoxDomaine.addItem("logement");  
               jComboBoxDomaine.addItem("agriculture");
               jComboBoxDomaine.addItem("commerce");
               jComboBoxDomaine.addItem("education");
               jComboBoxDomaine.addItem("indestrie");
               jComboBoxDomaine.addItem("transport");
               jComboBoxDomaine.addItem("santé");
               jComboBoxDomaine.addItem("autre"); 
            }
           else if((resp.getDomaineTravail().equals(Domaine.industrie))){
               jComboBoxDomaine.removeAllItems();
                jComboBoxDomaine.addItem("indestrie");
                jComboBoxDomaine.addItem("agriculture");
                jComboBoxDomaine.addItem("commerce");
                jComboBoxDomaine.addItem("education");
               jComboBoxDomaine.addItem("logement");  
               jComboBoxDomaine.addItem("transport");
               jComboBoxDomaine.addItem("santé");
               jComboBoxDomaine.addItem("autre");
           }
           else if((resp.getDomaineTravail().equals(Domaine.education))){
               jComboBoxDomaine.removeAllItems();
               jComboBoxDomaine.addItem("education");
               jComboBoxDomaine.addItem("agriculture");
               jComboBoxDomaine.addItem("commerce");
               jComboBoxDomaine.addItem("indestrie");
                jComboBoxDomaine.addItem("logement");  
                jComboBoxDomaine.addItem("transport");
                jComboBoxDomaine.addItem("santé");
                jComboBoxDomaine.addItem("autre"); 
           }
           else if(resp.getDomaineTravail().equals(Domaine.commerce)){
               jComboBoxDomaine.removeAllItems();
               jComboBoxDomaine.addItem("commerce");
               jComboBoxDomaine.addItem("agriculture");
               jComboBoxDomaine.addItem("education");
               jComboBoxDomaine.addItem("indestrie");
                jComboBoxDomaine.addItem("logement");  
                jComboBoxDomaine.addItem("transport");
                jComboBoxDomaine.addItem("santé");
                jComboBoxDomaine.addItem("autre");
           }
           else if(resp.getDomaineTravail().equals(Domaine.agriculture)){
               jComboBoxDomaine.removeAllItems();
               jComboBoxDomaine.addItem("agriculture");
               jComboBoxDomaine.addItem("commerce");
               jComboBoxDomaine.addItem("education");
               jComboBoxDomaine.addItem("santé");    
               jComboBoxDomaine.addItem("logement");  
               jComboBoxDomaine.addItem("transport");
               jComboBoxDomaine.addItem("indestrie");
               jComboBoxDomaine.addItem("autre");
           }
           else {
               jComboBoxDomaine.removeAllItems();
               jComboBoxDomaine.addItem("autre");  
               jComboBoxDomaine.addItem("agriculture");
               jComboBoxDomaine.addItem("commerce");
               jComboBoxDomaine.addItem("education");
                jComboBoxDomaine.addItem("indestrie");
                jComboBoxDomaine.addItem("logement");  
                jComboBoxDomaine.addItem("transport");
                jComboBoxDomaine.addItem("santé");
           }
          
    }//GEN-LAST:event_jButtonVerifiierActionPerformed

    private void jTextFieldPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenomActionPerformed

  
  
     
    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed

                Component frame = null; 
                int c=Integer.parseInt(jTextFieldCIN.getText()); 
                SimpleDateFormat sp=new SimpleDateFormat("yyyy/MM/dd");
      
           java.util.Date date_util = jDateChooser1.getDate();
           java.sql.Date date_sql = new java.sql.Date(date_util.getTime());
        //------------------------------------------------
           ResponsableDAO rd= new ResponsableDAO();
           Responsable r=new Responsable();
           r.setNom(jTextFieldNom.getText());
           r.setPrenom(jTextFieldPrenom.getText());
           r.setEmail(jTextFieldNouvAdresse.getText());
           r.setPwd(jTextFieldpwd.getText());
           r.setGrade(jTextFieldGrade.getText());
           
                            if(jComboBoxCategorie.getSelectedItem().equals("prive")){
                                   r.setCategorie(Categorie.prive);
                            }
                            else if(jComboBoxCategorie.getSelectedItem().equals("etatique")){
                                    r.setCategorie(Categorie.etatique);
                            }
                            else{
                                    r.setCategorie(Categorie.semiEtatique);
                            }
                       //-------------------------------------------------    
                            if(jComboBoxDomaine.getSelectedItem().equals("santé")){
                                    r.setDomaineTravail(Domaine.santé);
                            }
                            else if(jComboBoxDomaine.getSelectedItem().equals("education")){
                                r.setDomaineTravail(Domaine.education);  
                            }
                            else if(jComboBoxDomaine.getSelectedItem().equals("logement")){
                                r.setDomaineTravail(Domaine.logement);
                            }
                            else if(jComboBoxDomaine.getSelectedItem().equals("transport")){
                                r.setDomaineTravail(Domaine.transport);
                             }
                            else if(jComboBoxDomaine.getSelectedItem().equals("commerce")){
                                r.setDomaineTravail(Domaine.commerce);
                            }
                            else if(jComboBoxDomaine.getSelectedItem().equals("industrie")){
                                r.setDomaineTravail(Domaine.industrie);
                            }
                            else if(jComboBoxDomaine.getSelectedItem().equals("agriculture")){
                                r.setDomaineTravail(Domaine.agriculture);
                            }
                            else {
                                r.setDomaineTravail(Domaine.autre);
                            }
        
          
           r.setDateNaissance(date_sql);
           r.setTelephone(Integer.parseInt(jTextFieldTelephone.getText()));
           r.setAdresse(jTextFieldNouvAdresse.getText());
           r.setCin(c);
           rd.updateResponsable(r);
        
    }//GEN-LAST:event_jButtonValiderActionPerformed

    private void jTextFieldNouvAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNouvAdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNouvAdresseActionPerformed

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
         
  
          
   
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jButtonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonQuitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifierCompteResp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifierCompteResp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifierCompteResp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifierCompteResp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modifierCompteResp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccueil;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JButton jButtonVerifiier;
    private javax.swing.JComboBox jComboBoxCategorie;
    private javax.swing.JComboBox jComboBoxDomaine;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordFieldAncienPwd;
    private javax.swing.JPasswordField jPwdNouv2;
    private javax.swing.JTextField jTextFieldAncienMail;
    private javax.swing.JTextField jTextFieldCIN;
    private javax.swing.JTextField jTextFieldGrade;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldNouvAdresse;
    private javax.swing.JTextField jTextFieldNouvMail;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldTelephone;
    private javax.swing.JTextField jTextFieldpwd;
    // End of variables declaration//GEN-END:variables
}
